config/routes.rb
Rails4::Application.routes.draw do
  resources :pins

  devise_for :users
  get "pages/home"
  root "pins#index"

  get 'about'=>'pages#about'

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base

	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

 

  	protected

 	def configure_permitted_parameters
   		devise_parameter_sanitizer.for(:sign_up) << :name
   		devise_parameter_sanitizer.for(:account_update) << :name
   		devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email) }
 	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about

  end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :destroy, :update]
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def authorize
      @pin = current_user.pins.find_by(id: params[:id])

      redirect_to pins_path, notice: 'you are not authorised ' if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description,:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layout_partials/_header.html.erb
<div class="navbar navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" >Pintresting</a>
        </div>

        <div class="navbar-collapse collapse ">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'home', root_path %></li>
            <li><%= link_to 'about', about_path %></li>

            <% if user_signed_in? %>
              <li><%= link_to 'Add Pin', new_pin_path %></li>
              <li><%= link_to 'Account Settings', edit_user_registration_path %></li>
              <li><%= link_to 'Log Out',destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'sign In',new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
        
      </div>
    </div>

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>

	<%= render 'layout_partials/header' %>

    <div class="container">
    	<% flash.each do |name,msg| %>
    		<%= content_tag(:div,msg, class: "alert alert-info") %>
    	<% end %>

		<%= yield %>
	</div>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron">
  <div class="container">
    <h2 class="h2">Welcome to Pintresting Find More Pictures</h2>
    <div class="login">
    		<%= link_to 'Login',new_user_session_path, class:'btn btn-warning btn-lg' %>
    		<%= link_to 'SignUp',new_user_registration_path, class:'btn btn-success btn-lg' %>
  	</div>
  </div>
</div>

app/views/pages/about.html.erb
<h1>About us </h1>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h2 class="h2">Welcome to Pintresting Find More Pictures</h2>
    <div class="login">
    	<% if user_signed_in? %>
    		#do something
    	<% else %>
    		<%= link_to 'Login',new_user_session_path, class:'btn btn-warning btn-lg' %>
    		<%= link_to 'SignUp',new_user_registration_path, class:'btn btn-success btn-lg' %>
    	<% end %>
  	</div>
</div>

app/views/pins/_form.html.erb
  <%= form_for(@pin, html: {multipart: true}) do |f| %>
    <% if @pin.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

        <ul>
        <% @pin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class='form-group'>
      <%= f.label :Image %></br>
      <%= f.file_field :image, class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= f.label :description %></br>
      <%= f.text_field :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit(class: 'btn btn-primary') %>
    </div>
  <% end %>

app/views/pins/edit.html.erb
<div class="panel panel-primary">
	<div class="panel-heading panel-text">
		<h6>Edit pin</h6>
	</div>

	<div class="panel-body">
		<%= render 'form' %>
	</div>

	<div class="panel-footer">

		<%= link_to 'Show', @pin, class: 'btn btn-primary' %> |
		<%= link_to 'Back', pins_path, class: 'btn btn-danger' %>
	</div>
</div>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class=" box panel panel-default">
      <div class="panel-body">
        <%= link_to image_tag(pin.image.url(:medium)), pin_path(pin)%>
      </div>

      <div class="panel-footer">
          <%= pin.description %>
          <%= pin.user.email if pin.user %>
          
          <% if pin.user == current_user %>
            <%= link_to  edit_pin_path(pin), class: 'btn btn-warning'  do %>
                <span class="glyphicon glyphicon-edit"></span>edit
            <% end %>

            <%= link_to  pin, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
              <span class="glyphicon glyphicon-trash"></span>delete
            <% end %>

          <% end %>
      </div>
    </div>
  <% end %>
</div>
      

app/views/pins/new.html.erb
<div class="panel panel-primary">
	<div class="panel-heading panel-text">
		<h6>New pin</h6>
	</div>

	<div class="panel-body">
		<%= render 'form' %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Back', pins_path , class: 'btn btn-danger'%>
	</div>
</div>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path, class: 'btn btn-primary' %>
<div class="row">
  <div class="col-md-offset-2 col-md-4">
	<div class="panel panel-success">
		<div class="panel-heading center">
			<%= image_tag @pin.image.url(:medium), class: 'center' %>
		</div>

		<div class="panel-body">
			<p>
			  <%= @pin.description %>
			</p>
			<p>
			  <%= @pin.user.email if @pin.user%>
			</p>
		</div>

		<div class="panel-footer">
			<% if @pin.user == current_user %>
				<%= link_to edit_pin_path(@pin), class: 'btn btn-warning' do %>
					<span class="glyphicon glyphicon-edit"></span>edit
				<% end %> 
			<% end  %>
			
		</div>
</div>